CREATE DATABASE request;
USE request;
CREATE TABLE USERS(
  USERNAME VARCHAR (20)   NOT NULL,
  FIRSTNAME VARCHAR (20)  NOT NULL,
  LASTNAME  VARCHAR (20)  NOT NULL,
  PASSWORD CHAR (25)  NOT NULL,
  SALT  CHAR (10) NOT NULL,
  ADDRESS  CHAR (25),
  PRIMARY KEY (USERNAME)
);
CREATE TABLE REQUESTS(
  ID    INT             NOT NULL,
  DATE DATETIME         NOT NULL,
  SENDER  INT           NOT NULL,
  RECIEVER  INT         NOT NULL,
  AMOUNT DOUBLE(10, 2)  NOT NULL,
  DESCRIPTION   CHAR (25),
  PRIMARY KEY (ID)
);
CREATE TABLE LEDGER(
  ID    INT   NOT NULL,
  DATE  DATETIME  NOT NULL,
  USERID  INT   NOT NULL,
  DEBIT   DOUBLE(10, 2),
  CREDIT  DOUBLE(10, 2),
  PRIMARY KEY (ID)
);
CREATE TABLE ACTIVE(
  SENDER    INT   NOT NULL,
  RECIEVER  INT   NOT NULL,
  AMOUNT  DOUBLE(10, 2) NOT NULL,
  PRIMARY KEY(SENDER)
);
